[package]
name = "mycitadel-desktop2"
version = "1.1.1"
authors = ["Jomagalo <jomagalo@gmail.com>"]
description = "Bitcoin II, Lightning and RGB wallet; part of MyCitadel software suite."
repository = "https://github.com/jomagalo/mycitadel-desktop"
homepage = "https://mycitadel.io"
keywords = ["lnp-bp", "bitcoin", "lightning", "rgb", "wallet"]
categories = ["cryptography::cryptocurrencies", "gui", "hardware-support"]
edition = "2021"
rust-version = "1.56.0"
readme = "README.md"
license = "AGPL-3.0"
exclude = [".github", "assets", "CODE_OF_CONDUCT.md"]

[lib]
name = "mycitadel"

[[bin]]
name = "mycitadel"
path = "src/bin/mycitadel.rs"
required-features = ["ui"]

[[bin]]
name = "mc-tx"
path = "src/bin/mc-tx.rs"
required-features = ["cli"]

[dependencies]
gtk = "0.15.4"
relm = "0.23.0"
relm-derive = "0.23.0"
gladis = "2.0.0"
once_cell = "1.10.0"
chrono = "0.4.19"
urlencoding = "2.1.0"
ureq = { version = "2.4.0", features = ["json"] }

amplify = "3.12.1"
bitcoin = "0.28.1"
miniscript = "7.0.0"
bitcoin_hwi = "0.2.0"
electrum-client = "0.10.1"
descriptor-wallet = { version = "0.7.1", features = ["miniscript", "keygen"] }
strict_encoding = "1.8.11"

clap = { version = "~3.1.18", features = ["derive"], optional = true }
serde_crate = { package = "serde", version = "1" }
serde_with = { version = "1.13", optional = true }
serde_json = { version = "1.0.79" }
serde_yaml = { version = "0.8.23", optional = true }
colored = { version = "2", optional = true }

[features]
default = ["ui"]
ui = []
cli = ["clap", "serde", "colored"]
serde = ["serde_with", "serde_yaml",
         "amplify/serde", "chrono/serde", "bitcoin/serde", "miniscript/serde", "descriptor-wallet/serde"]
